name: Golang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up 
      uses: actions/setup-go@v1
      with:
        go-version: 1.20

    - name: Build 
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
  goLinter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.20'
      - uses: actions/checkout@v1
      - name: linter
        uses: linter/linter-action@v1
        
